stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./7.2-fpm/Dockerfile
      buildContext: ./7.2-fpm
      tag: php-fpm:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
