kind: Service
apiVersion: v1
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    app: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      volumes:
      - name: magento2-data
        persistentVolumeClaim:
                claimName: appdata
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: php-fpm
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        volumeMounts:
           - name: magento2-data
             mountPath: "/var/www/magento"
        ports:
        - containerPort: 9000
